define({
  root: ({
    _widgetLabel: "Distance and Direction",
    tabLineTitle: "Line",
    tabCircleTitle: "Circle",
    tabEllipseTitle: "Ellipse",
    tabRingsTitle: "Rings",
    multipleNotationsMessage: " notations that match your input. Please confirm which you would like to use:",
    invalidCoordinateMessage: "Invalid Coordinate",
    confirmInputNotationMessage: "Confirm Input Notation",
    prefixSuffixMessage: "The input coordinate has been detected as having both a prefix and suffix for the latitude or longitude value, returned coordinate is based on the prefix.",
    rememberDecisionMessage: "Remember my decision and do not ask again.<br/>",
    majorAxisTooltipMessage: "Click length of major axis",
    minorAxisTooltipMessage: "Move mouse back to start position to set minor axis & finish drawing ellipse",
    clickToFinishLineMessage: "Click to finish drawing line",
    doubleClickEllipseMesage: "Double-click to finish drawing range rings",
    invalidCoordinateTypeMessage: "Unable to determine input coordinate type. Please check your input",
    noCenterPointSetMessage: "No center point set. Please check your input",
    ellipseMajorAxis: "Major Axis",
    ellipseMinorAxis: "Minor Axis",
    degreesRangeMessage: "Value must be between 0 and 360",
    millsRangeMessage: "Value must be between 0 and 6400",
    lengthLabel: "Length",
    angleLabel: "Angle",
    startPointLabel: "Start Point",
    endPointLabel: "End Point",
    centerPointLabel: "Center Point",
    distanceTableErrorMessage: "Distance table is empty or contains invalid values. Ensure all distances are numeric.",
    doubleClickRangeMessage: "Double click to add value",
    setCoordFormatStringMessage: "Set Coordinate Format String",
    prefixMessage:"Add '+/-' prefix to positive and negative numbers",
    ddLabel: "DD",
    ddmLabel: "DDM",
    dmsLabel: "DMS",
    garsLabel: "GARS",
    georefLabel: "GEOREF",
    mgrsLabel: "MGRS",
    usngLabel: "USNG",
    utmLabel: "UTM",
    utmhLabel: "UTM (H)",
    circleTitle: "Create Circle From",
    radiusLabel: "Radius",
    diameterLabel: "Diameter",
    startPointPlaceHolderLabel: "Enter Coordinates",
    formatInputLabel: "Format Input",
    drawCircleLabel: "Draw Circle",
    drawLineLabel: "Draw Line",
    createCircleInteractivelyLabel: "Create Circle Interactively",
    rangeErrorMessage: "Invalid radius or diameter",
    numericInvalidMessage: "Please enter a numeric value",
    timeLabel: "Time",
    invalidTimeMessage: "Invalid time value",
    hoursLabel: "Hours",
    minutesLabel: "Minutes",
    secondsLabel: "Seconds",
    rateLabel: "Rate",
    invalidDistanceMessage: "Invalid distance value",
    feetSecondsLabel: "Feet / second",
    feetHourLabel: "Feet / hour",
    kmSecondLabel: "Kilometers / second",
    kmHourLabel: "Kilometer / hour",
    metersSecondLabel: "Meters / second",
    metersHourLabel: "Meters / hour",
    milesSecondLabel: "Miles / second",
    milesHourLabel: "Miles / hour",
    nauticalMilesSecondLabel: "Nautical Miles / second",
    nauticalMilesHourLabel: "Nautical Miles / hour",
    clearGraphicsLabel: "Clear Graphics",
    ellipseTypeLabel: "Ellipse Type",
    ellipseSemiLabel: "Semi",
    ellipseFullLabel: "Full",
    drawEllipseLabel: "Draw Ellipse",
    createEllipseInteractively: "Create Ellipse Interactively",
    axisLabel: "Axis",
    majorRadiusLabel: "Major (Radius)",
    axisErrorMessage: "Value must be greated than 0",
    minorRadiusLabel: "Minor (Radius)",
    orientationLabel: "Orientation",
    orientationErrorMessage: "Value must be between 0 and 360",
    warningMessage: "Warning: Graphics generated using the ellipse tool are not geodetic",
    fromLabel: "From",
    distanceBearingLabel: "Distance and Bearing",
    pointsLabel: "Points",
    createLineInteractively: "Create Line Interactively",
    lengthLabel: "Length",
    lineLengthErrorMessage: "Invalid Line Length",
    degreesLabel: "Degress",
    milsLabel: "Mils",
    lineTypeLabel: "Type",
    interactiveLabel: "Interactive",
    fixedLabel: "Fixed",
    originLabel: "Origin",
    cumulativeLabel: "Cumulative",
    numberOfRingsLabel: "Number of Rings",
    ringsErrorMessage: "Invalid number of rings",
    distanceBetweenRingsLabel: "Distance Between Rings",
    ringsDecimalErrorMessage: "Enter a numeric value to 2 decimal places",
    distanceUnitsLabel: "Distance Units",
    distancesLabel: "Distances",
    numberOfRadialsLabel: "Number of Radials",
    upLabel: "Up",
    downLabel: "Down",
    deleteLabel: "Delete",
    radialsErrorMessage: "Invalid number of radials. The maximum allowed is 360",
    addPointLabel: "Add Point",
    valueLabel: "Value",
    valueText: "Enter Value",
    actionLabel: "Action"
  }),
  "ar": 0,
  "bs": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "hi": 0,
  "hr": 0,
  "it": 0,
  "id": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sl": 0,
  "sr": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0,
  "zh-hk": 0,
  "zh-tw": 0
});
